; Generated by MiniC compiler
.org 0x200

; --- main ---
    LDA #1
    STA [0x00]    ; prev
    LDA #1
    STA [0x01]    ; curr
    LDA #0
    STA [0x02]    ; next
    LDA #11
    STA [0x03]    ; count
    LDA [0x00]    ; prev
    OUT
    LDA [0x01]    ; curr
    OUT
__while_1:
    LDA [0x03]    ; count
    PSA             ; save left
    LDA #0
    MVB             ; B = right
    PPA             ; A = left
    CMP             ; flags = A - B
    JC __endwhile_2
    JZ __endwhile_2
    LDA [0x00]    ; prev
    PSA             ; save left
    LDA [0x01]    ; curr
    MVB             ; B = right
    PPA             ; A = left
    ADD
    STA [0x02]    ; next
    LDA [0x02]    ; next
    OUT
    LDA [0x01]    ; curr
    STA [0x00]    ; prev
    LDA [0x02]    ; next
    STA [0x01]    ; curr
    LDA [0x03]    ; count
    PSA             ; save left
    LDA #1
    MVB             ; B = right
    PPA             ; A = left
    SUB
    STA [0x03]    ; count
    JMP __while_1
__endwhile_2:
    HLT

