; Generated by MiniC compiler
.org 0x0000

; --- main ---
    LDA #1
    STA [0x8000]    ; prev
    LDA #1
    STA [0x8001]    ; curr
    LDA #0
    STA [0x8002]    ; next
    LDA #11
    STA [0x8003]    ; count
    LDA [0x8000]    ; prev
    OUT
    LDA [0x8001]    ; curr
    OUT
__while_1:
    LDA [0x8003]    ; count
    PSA             ; save left
    LDA #0
    MVB             ; B = right
    PPA             ; A = left
    CMP             ; flags = A - B
    JC __endwhile_2
    JZ __endwhile_2
    LDA [0x8000]    ; prev
    PUSH A          ; save left
    LDA [0x8001]    ; curr
    MVB             ; B = right
    POP A           ; A = left
    ADD
    STA [0x8002]    ; next
    LDA [0x8002]    ; next
    OUT
    LDA [0x8001]    ; curr
    STA [0x8000]    ; prev
    LDA [0x8002]    ; next
    STA [0x8001]    ; curr
    LDA [0x8003]    ; count
    PUSH A          ; save left
    LDA #1
    MVB             ; B = right
    POP A           ; A = left
    SUB
    STA [0x8003]    ; count
    JMP __while_1
__endwhile_2:
    HLT

