; Generated by MiniC compiler
.org 0x0000

; --- main ---
    LDA #7
    STA [0x8000]    ; x
    LDA #6
    STA [0x8001]    ; y
    LDA [0x8000]    ; x
    PUSH A          ; push arg
    LDA [0x8001]    ; y
    PUSH A          ; push arg
    CAL __fn_multiply
    ; caller cleans up stack (2 args)
    PUSH A          ; temporarily save return val
    POP B           ; discard arg
    POP B           ; discard arg
    POP A           ; restore return val
    STA [0x8002]    ; product_lo
    LDA [0x8002]    ; product_lo
    OUT
    HLT

; --- function multiply ---
__fn_multiply:
    PUSH A          ; save ret high
    PUSH B          ; save ret low
    LSA 4            ; load arg multiplier
    STA [0x8003]    ; param multiplier
    LSA 3            ; load arg multiplicand
    STA [0x8004]    ; param multiplicand
    LDA #0
    STA [0x8005]    ; result_lo
    LDA #0
    STA [0x8006]    ; result_hi
    LDA [0x8004]    ; multiplicand
    STA [0x8007]    ; mc_lo
    LDA #0
    STA [0x8008]    ; mc_hi
__while_1:
    LDA [0x8003]    ; multiplier
    PSA             ; save left
    LDA #0
    MVB             ; B = right
    PPA             ; A = left
    CMP             ; flags = A - B
    JC __endwhile_2
    JZ __endwhile_2
    LDA [0x8003]    ; multiplier
    PUSH A          ; save left
    LDA #1
    MVB             ; B = right
    POP A           ; A = left
    AND
    PSA             ; save left
    LDA #1
    MVB             ; B = right
    PPA             ; A = left
    CMP             ; flags = A - B
    JNZ __else_3
    LDA [0x8005]    ; result_lo
    PUSH A          ; save left
    LDA [0x8007]    ; mc_lo
    MVB             ; B = right
    POP A           ; A = left
    ADD
    STA [0x8005]    ; result_lo
    LDA [0x8005]    ; result_lo
    PSA             ; save left
    LDA [0x8007]    ; mc_lo
    MVB             ; B = right
    PPA             ; A = left
    CMP             ; flags = A - B
    JNC __else_5
    LDA [0x8006]    ; result_hi
    PUSH A          ; save left
    LDA #1
    MVB             ; B = right
    POP A           ; A = left
    ADD
    STA [0x8006]    ; result_hi
__else_5:
    LDA [0x8006]    ; result_hi
    PUSH A          ; save left
    LDA [0x8008]    ; mc_hi
    MVB             ; B = right
    POP A           ; A = left
    ADD
    STA [0x8006]    ; result_hi
__else_3:
    LDA [0x8003]    ; multiplier
    PUSH A          ; save left
    LDA #1
    MVB             ; B = right
    POP A           ; A = left
    SHR
    STA [0x8003]    ; multiplier
    LDA [0x8007]    ; mc_lo
    STA [0x8009]    ; old_mc_lo
    LDA [0x8007]    ; mc_lo
    PUSH A          ; save left
    LDA #1
    MVB             ; B = right
    POP A           ; A = left
    SHL
    STA [0x8007]    ; mc_lo
    LDA [0x8008]    ; mc_hi
    PUSH A          ; save left
    LDA #1
    MVB             ; B = right
    POP A           ; A = left
    SHL
    STA [0x8008]    ; mc_hi
    LDA [0x8009]    ; old_mc_lo
    PSA             ; save left
    LDA #127
    MVB             ; B = right
    PPA             ; A = left
    CMP             ; flags = A - B
    JC __else_7
    JZ __else_7
    LDA [0x8008]    ; mc_hi
    PUSH A          ; save left
    LDA #1
    MVB             ; B = right
    POP A           ; A = left
    ADD
    STA [0x8008]    ; mc_hi
__else_7:
    JMP __while_1
__endwhile_2:
    LDA [0x8006]    ; result_hi
    OUT
    LDA [0x8005]    ; result_lo
    POP C           ; restore ret low
    POP D           ; restore ret high
    RET
    POP C           ; restore ret low
    POP D           ; restore ret high
    RET

