; Generated by MiniC compiler
.org 0x0000

; --- main ---
    LDA #7
    STA [0x8000]    ; x
    LDA #6
    STA [0x8001]    ; y
    LDA [0x8000]    ; x
    PUSH A          ; push arg
    LDA [0x8001]    ; y
    PUSH A          ; push arg
    CAL __fn_multiply
    ; caller cleans up stack (2 args)
    PUSH A          ; temporarily save return val
    POP B           ; discard arg
    POP B           ; discard arg
    POP A           ; restore return val
    STA [0x8002]    ; product
    LDA [0x8002]    ; product
    OUT
    HLT

; --- function multiply ---
__fn_multiply:
    PUSH A          ; save ret high
    PUSH B          ; save ret low
    LSA 4            ; load arg a
    STA [0x8003]    ; param a
    LSA 3            ; load arg b
    STA [0x8004]    ; param b
    LDA #0
    STA [0x8005]    ; result
__while_1:
    LDA [0x8004]    ; b
    PSA             ; save left
    LDA #0
    MVB             ; B = right
    PPA             ; A = left
    CMP             ; flags = A - B
    JC __endwhile_2
    JZ __endwhile_2
    LDA [0x8005]    ; result
    PUSH A          ; save left
    LDA [0x8003]    ; a
    MVB             ; B = right
    POP A           ; A = left
    ADD
    STA [0x8005]    ; result
    LDA [0x8004]    ; b
    PUSH A          ; save left
    LDA #1
    MVB             ; B = right
    POP A           ; A = left
    SUB
    STA [0x8004]    ; b
    JMP __while_1
__endwhile_2:
    LDA [0x8005]    ; result
    POP C           ; restore ret low
    POP D           ; restore ret high
    RET
    POP C           ; restore ret low
    POP D           ; restore ret high
    RET

