; Generated by MiniC compiler
.org 0x0000

; --- main ---
    LDA #7
    STA [0x8000]    ; x
    LDA #6
    STA [0x8001]    ; y
    LDA [0x8000]    ; x
    PUSH A          ; push arg
    LDA [0x8001]    ; y
    PUSH A          ; push arg
    CAL __fn_multiply
    ; caller cleans up stack (2 args)
    PUSH A          ; temporarily save return val
    POP B           ; discard arg
    POP B           ; discard arg
    POP A           ; restore return val
    STA [0x8002]    ; product_lo
    LDA [0x8002]    ; product_lo
    OUT
    HLT

; --- function multiply ---
__fn_multiply:
    PUSH A          ; save ret high
    PUSH B          ; save ret low
    LSA 4            ; load arg multiplier
    STA [0x8003]    ; param multiplier
    LSA 3            ; load arg multiplicand
    STA [0x8004]    ; param multiplicand
    LDA #0
    STA [0x8005]    ; result_lo
    LDA #0
    STA [0x8006]    ; result_hi
    LDA [0x8004]    ; multiplicand
    STA [0x8007]    ; mc_lo
    LDA #0
    STA [0x8008]    ; mc_hi
    LDA #8
    STA [0x8009]    ; i

__mult_loop:
        ; Shift multiplier right, lowest bit goes into Carry flag
        LDA [0x8003]
        SHR
        STA [0x8003]
        JNC skip_add
        
        ; If Carry was 1, add multiplicand to result
        LDA [0x8005]
        LDB [0x8007]
        ADD
        STA [0x8005]
        
        ; Manual add-with-carry for high byte
        JNC no_carry_res
        LDA [0x8006]
        LDB #1
        ADD
        STA [0x8006]
no_carry_res:
        LDA [0x8006]
        LDB [0x8008]
        ADD
        STA [0x8006]
        
skip_add:
        ; Shift multiplicand left by 1 (16-bit shift)
        LDA [0x8007]
        SHL
        STA [0x8007]
        JNC no_carry_mc
        ; If lo byte shift overflowed, shift hi byte and add 1
        LDA [0x8008]
        SHL
        LDB #1
        ADD
        STA [0x8008]
        JMP mc_shifted
no_carry_mc:
        LDA [0x8008]
        SHL
        STA [0x8008]
mc_shifted:

        ; Loop 8 times
        LDA [0x8009]
        LDB #1
        SUB
        STA [0x8009]
        JNZ __mult_loop
    
    LDA [0x8006]    ; result_hi
    OUT
    LDA [0x8005]    ; result_lo
    POP C           ; restore ret low
    POP D           ; restore ret high
    RET
    POP C           ; restore ret low
    POP D           ; restore ret high
    RET

