; Generated by MiniC compiler
.org 0x0000

; --- main ---
    LDA #7
    STA [0x8000]    ; x
    LDA #6
    STA [0x8001]    ; y
    LDA [0x8001]    ; y
    STA [0x8003]    ; pass arg 1
    LDA [0x8000]    ; x
    CAL __fn_multiply
    STA [0x8002]    ; product
    LDA [0x8002]    ; product
    OUT
    HLT

; --- function multiply ---
__fn_multiply:
    STA [0x8004]    ; param a
    LDA [0x8003]    ; load arg b
    STA [0x8005]    ; param b
    LDA #0
    STA [0x8006]    ; result
__while_1:
    LDA [0x8005]    ; b
    PSA             ; save left
    LDA #0
    MVB             ; B = right
    PPA             ; A = left
    CMP             ; flags = A - B
    JC __endwhile_2
    JZ __endwhile_2
    LDA [0x8006]    ; result
    PSA             ; save left
    LDA [0x8004]    ; a
    MVB             ; B = right
    PPA             ; A = left
    ADD
    STA [0x8006]    ; result
    LDA [0x8005]    ; b
    PSA             ; save left
    LDA #1
    MVB             ; B = right
    PPA             ; A = left
    SUB
    STA [0x8005]    ; b
    JMP __while_1
__endwhile_2:
    LDA [0x8006]    ; result
    RET
    RET

